In [4]:
import numpy as np

## Basic numpy 1-D/2-D Array

In [8]:
np.array([1,2,3,4,5,6,7,8]).shape

(8,)

In [44]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [47]:
np.full((10),2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [51]:
np.arange(2,7)[::3]

array([2, 5])

In [52]:
np.full((10),3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [53]:
np.array([[1,3,4,5,6],[5,6,7,8,1]])[0:2,0:4]

array([[1, 3, 4, 5],
       [5, 6, 7, 8]])

## Universal Functions in Nunmpy

In [27]:
#SQRT
np1=np.array([1,2,3,4,5,6,7,8,9])

In [26]:
np.sqrt(np1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
#Absolute Function
np2=np.array([1,2,-3,4,5.4,6,-7])
np.absolute(np2)

array([1. , 2. , 3. , 4. , 5.4, 6. , 7. ])

In [38]:
#Exponents
np.exp(np2)

array([2.71828183e+00, 7.38905610e+00, 4.97870684e-02, 5.45981500e+01,
       2.21406416e+02, 4.03428793e+02, 9.11881966e-04])

In [39]:
# Min/Max
np.max(np2)

6.0

In [40]:
np.min(np2)

-7.0

In [44]:
#Sign in numpy (-1 for -ive and +1 for +ive)
np.sign(np2)

array([ 1.,  1., -1.,  1.,  1.,  1., -1.])

## Copy vs View

In [63]:
#View - Whatever you change in og gets reflected in the copy and viceversa
np3=np.array([1,2,3,4,5,6,7,8,9,1])

In [46]:
np4=np3.view()

In [51]:
np3[0]=21

In [52]:
np3==np4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [54]:
#Copy - Chnges made to OG dosent affect the copy and vice versa
np5=np.array([2,3,6,78,6])
np6=np5.copy()

In [55]:
np5[0]=976

In [56]:
np6==np5

array([False,  True,  True,  True,  True])

In [60]:
np6[-1]=9

In [62]:
np5

array([976,   3,   6,  78,   6])

In [61]:
np6

array([ 2,  3,  6, 78,  9])

## Shape & Reshape 

In [56]:
#Products of reshape numbers shoulbe be equal to the len() of np array
np7=np.array([1,2,3,4,5,6,7,8,9,10,4,5])

In [57]:
np7.shape

(12,)

In [58]:
np7r=np7.reshape(2,3,2)
np7r

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [ 4,  5]]])

In [93]:
np7r.reshape(-4)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  5])

## Iterating through np arrays

In [107]:
#1-D
np8=np.array([1,2,3,4,5,6,7,8,9,10])

In [96]:
for i in np8:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [106]:
#2-D
np9 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [100]:
for i in np9:
    for j in i:
        print(j)
    print('-------------------------')

1
2
3
4
5
-------------------------
6
7
8
9
10
-------------------------


In [104]:
#3-D
np10=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
np10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [105]:
np10.shape

(2, 2, 2)

In [109]:
for i in np10:
    for j in i:
        for k in j:
            print(k)
        print('****')
    print('--------------')

1
2
****
3
4
****
--------------
5
6
****
7
8
****
--------------


In [111]:
#Easier way for loops np.nditer()

for i in np.nditer(np10):
    print(i)

1
2
3
4
5
6
7
8


## Sorting Numpy Arrays 

In [120]:
#Ascending
np11=np.array([3,6,2,1,90,4,7,3,-1])

In [119]:
np.sort(np11)

array([-1,  1,  2,  3,  3,  4,  6,  7, 90])

In [5]:
np12=np.array(['swastik','aomika','swagat','subham', 'pattnaik','subham' ,'samal'])

In [6]:
print(np12)
print(np.sort(np12))

['swastik' 'aomika' 'swagat' 'subham' 'pattnaik' 'subham' 'samal']
['aomika' 'pattnaik' 'samal' 'subham' 'subham' 'swagat' 'swastik']


In [62]:
#Sort Desceding
np.sort(np12)[::-1]

array(['swastik', 'swagat', 'subham', 'subham', 'samal', 'pattnaik',
       'aomika'], dtype='<U8')

In [64]:
#IN 2D Array Sort will sort in each row
np13=np.array([[3,1,2,-1],[0,9,1,7]])

In [65]:
np13

array([[ 3,  1,  2, -1],
       [ 0,  9,  1,  7]])

In [66]:
np.sort(np13)

array([[-1,  1,  2,  3],
       [ 0,  1,  7,  9]])

## Searching Numpy Arrays 

In [24]:
np14=np.array([1,2,3,3,3,3,4,5,6,7,6,7,7,7,8,9,0])

In [9]:
s=np.where(np14==3)

In [16]:
np14[s[0]]

array([3, 3, 3, 3])

In [25]:
#Printing Even numbers
y=np.where(np14%2==0)
y

(array([ 1,  6,  8, 10, 14, 16], dtype=int64),)

In [26]:
np14[y[0]]

array([2, 4, 6, 6, 8, 0])

In [27]:
#Printing Odd numbers
y1=np.where(np14%2 != 0)
y1

(array([ 0,  2,  3,  4,  5,  7,  9, 11, 12, 13, 15], dtype=int64),)

In [28]:
np14[y1[0]]

array([1, 3, 3, 3, 3, 5, 7, 7, 7, 7, 9])

## Filtering Numpy arrays

In [29]:
np15=np.array([1,2,3,4,5])

In [30]:
c=[True,True,False,False,False]

In [31]:
np15[c]

array([1, 2])

In [35]:
#Long Way Filtering
m=[]
for i in np15:
    if i%2==0:
        m.append(True)
    else:
        m.append(False)

In [36]:
m

[False, True, False, True, False]

In [37]:
np15[m]

array([2, 4])

In [43]:
#Shortcut
np15[np15%2==0]

array([2, 4])